version: '3.8'

services:
  media-assistant-frontend:
    image: ghcr.io/alex1981-tech/vidnova-music-control/frontend:latest
    container_name: media-assistant-frontend
    restart: unless-stopped
    ports:
      - "8096:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - media-assistant-network

networks:
  media-assistant-network:
    driver: bridge
